# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rae' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rae
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'raeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rae-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rae-tvOS

  target 'rae-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
